package battleship;

import java.util.ArrayList;

import battleship.entities.Aircraft;
import battleship.entities.Battleship;
import battleship.entities.Cruiser;
import battleship.entities.Destroyer;
import battleship.entities.Ship;
import battleship.entities.Submarine;
import battleship.global.Constant;


public class AI {

	@SuppressWarnings("rawtypes")
	public static Grid autoGeneratedGrid(int ship_amount[]) throws Exception {
		int maxAmount[] = new int[] {Constant.AIRCRAFTMAX,Constant.BATTLESHIPMAX,Constant.CRUISERMAX,Constant.DESTROYERMAX,Constant.SUBMARINEMAX};
		ArrayList<Ship> typeList = new ArrayList<Ship>();
		typeList.add(new Aircraft());
		typeList.add(new Battleship());
		typeList.add(new Cruiser());
		typeList.add(new Destroyer());
		typeList.add(new Submarine());
		
		if (ship_amount.length != 5) {
			throw new Exception(
					"Lenght of ship_amount isn\'t equal to 5. Must be in this order: Aircraft Carrier, Battleship, Cruiser, Destroyer, Submarine.");
		}

		for(int i=0; i<maxAmount.length; i++){
			if(ship_amount[i]>maxAmount[i]){
				String name = typeList.get(i).getClass().getSimpleName();
				throw new Exception("The ship amount of " + name + " specified in parameter is greater than " + maxAmount[i] + " defined in the file Constant.java");
			}
		}

		Grid auto_generated_grid = new Grid(Grid.BLANK_GRID);
		
		for (int i = 0; i < typeList.size(); i++) {
			boolean placing_failed = false;
			for (int j = 0; j < ship_amount[i]; j++) {
				int fail_counter = 0;
				String name = typeList.get(i).getClass().getName();
				Class cl = Class.forName(name);			
				do {
					placing_failed = false;
					Object new_ship = null;
					try {
						new_ship = cl.newInstance();
						auto_generated_grid.placeShip((Ship)new_ship);
					} catch (Exception e) {
						System.err
								.println("Failed to place the random generated " + cl.getSimpleName() + " "
										+ (j+1) + ".");
						e.printStackTrace();
						placing_failed = true;
						fail_counter++;
						if(fail_counter > 100){
							String error = "The computer can't find a suitable grid configuration for these parameters: ";
							for(int x = 0; x<ship_amount.length; x++){
								error += (ship_amount[x] + " ");
							}
							error += ("\nStuck when adding " + cl.getSimpleName() + " "+ j + ".");
							throw new Exception(error);
						}
					} 
				} while (placing_failed);
			}
		}
		return auto_generated_grid;

	}

}
