package battleship;

import battleship.global.Constant;
import battleship.global.RandomSynchronized;
import battleship.network.*;

public class Game extends Thread {

	private static Game game = null;
	private boolean continueGame = false;
	private Screen screen = null;
	private Player player = null;
	private Player opponent = null;
	private NetworkListener networkListener = null;
	private NetworkWriter networkWriter = null;
	
	private double randomStart = RandomSynchronized.nextDouble(100);
	private boolean canPlay = false;
	
	private Game() {
		int[] shipAmount = {1,1,1,2,2};
		try {
			player = new Player("Josh", AI.autoGeneratedGrid(shipAmount));
			opponent = new Player("Vince", AI.autoGeneratedGrid(shipAmount));
		} catch (Exception e) {
			e.printStackTrace();
		}
		
	}

	public static Game getInstance() {
		if (game == null)
			game = new Game();
		return game;
	}
	
	public void run()
	{
		continueGame = true;
		
		networkListener = new NetworkListener(Constant.LISTENING_PORT);
		networkListener.start();
		
		screen = Screen.getInstance();
		SeparatorMessageQueue.getInstance().addMessageToQueue("En attente de connexion");
		screen.setVisible(true);
		
		while(continueGame)
		{
			try {
				Thread.sleep(500);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		}
		
		Screen.getInstance().dispose();
	}
	
	public void quit()
	{
		continueGame  = false;
		networkWriter.send("bye");
		networkListener.stopListening();
		networkWriter.stopWritting();
	}
	
	public Player getPlayer()
	{
		return player;
	}
	
	public Player getOpponent()
	{
		return opponent;
	}

	public void refresh() {
		screen.repaint();
		if(!opponent.getPlayerGrid().hasMoreShip())
			screen.showWonMenu();
		else if(!player.getPlayerGrid().hasMoreShip())
			screen.showLostMenu();
	}
	
	public void sendMessage(String message)
	{
		networkWriter.send(message);
	}

	public void connect() {
			connect("localhost");
	}
	
	public void connect(String hote) {
		if(networkWriter == null)
		{
			networkWriter = new NetworkWriter(hote,Constant.SENDING_PORT);
			networkWriter.start();
		}
	}

	public boolean canPlay() {
		return canPlay;
	}
	
	public void canPlay(boolean state)
	{
		canPlay = state;
		if(state)
			SeparatorMessageQueue.getInstance().addMessageToQueue("Your turn !");
		else
			SeparatorMessageQueue.getInstance().addMessageToQueue("Opponent turn !");
	}

	public double getRandomStarterPlayer()
	{
		return randomStart;
	}
	
	public void decideStarterPlayer(double opponentRand) {
		if (randomStart >opponentRand)
			canPlay(true);
		else
			canPlay(false);
	}

	public void endTurn() {
		canPlay(false);
		sendMessage("EOT");
	}
}
